name: typeorm.github.io
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
          registry-url: "https://registry.npmjs.org/"

      - name: Get Static
        run: |
          git clone https://github.com/typeorm/typeorm.github.io -b master --single-branch typeorm.github.io --depth 1

      - name: Deploy typeorm.github.io
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: typeorm.github.io
          PUBLISH_DIR: ./typeorm.github.io