name: Mirror

on: [push]

jobs:
  to_gitee:
    runs-on: ubuntu-latest
    if: github.repository == 'ant-design/ant-design'
    steps:
      - uses: actions/checkout@v1
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@gitee.com:ant-design/ant-design.git
          ssh_private_key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
