name: GitHub Actions Build and Deploy Document Static
on:
  push:
    branches:
      - master
jobs:
  job-react-native:
    runs-on: ubuntu-18.04
    steps:
      - name: Get react-native-doc Static
        uses: actions/checkout@v2
        with:
          repository: jaywcjlove/react-native-doc
          ref: gh-pages
          path: react-native-doc

      - name: Deploy react-native-doc
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: react-native
          PUBLISH_DIR: ./react-native-doc

  job-koajs:
    needs: job-react-native
    runs-on: ubuntu-18.04
    steps:
      - name: Get koajs Static
        uses: actions/checkout@v2
        with:
          repository: koajs/koajs.com
          ref: gh-pages
          path: koajs.com

      - name: Deploy koajs.com
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: koajs.com
          PUBLISH_DIR: ./koajs.com


  job-typeorm:
    needs: [job-react-native, job-koajs]
    runs-on: ubuntu-18.04
    steps:
      - name: Get typeorm Static
        uses: actions/checkout@v2
        with:
          repository: typeorm/typeorm.github.io
          ref: master
          path: typeorm.github.io

      - name: Deploy typeorm.github.io
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: typeorm.github.io
          PUBLISH_DIR: ./typeorm.github.io
        

  job-jest:
    needs: [job-react-native, job-koajs, job-typeorm]
    runs-on: ubuntu-18.04
    steps:
      - name: Get jestjs.io Static
        uses: actions/checkout@v2
        with:
          repository: facebook/jest
          ref: gh-pages
          path: jestjs.io

      - name: Deploy jestjs.io
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: jestjs.io
          PUBLISH_DIR: ./jestjs.io

  job-antd:
    needs: [job-react-native, job-koajs, job-typeorm, job-jest]
    runs-on: ubuntu-18.04
    steps:
      - name: Get ant.design Static
        uses: actions/checkout@v2
        with:
          repository: ant-design/ant-design
          ref: gh-pages
          path: ant.design

      - name: Deploy ant.design
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: ant.design
          PUBLISH_DIR: ./ant.design
        

  job-reactjs:
    needs: [job-react-native, job-koajs, job-typeorm, job-jest, job-antd]
    runs-on: ubuntu-18.04
    steps:
      - name: Get zh-hans.reactjs.org Static
        uses: actions/checkout@v2
        with:
          repository: reactjs/zh-hans.reactjs.org
          ref: gh-pages
          path: zh-hans.reactjs.org

      - name: Deploy zh-hans.reactjs.org
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: zh-hans.reactjs.org
          PUBLISH_DIR: ./zh-hans.reactjs.org
        

  job-element:
    needs: [job-react-native, job-koajs, job-typeorm, job-jest, job-antd, job-reactjs]
    runs-on: ubuntu-18.04
    steps:
      - name: Get element.eleme.io Static
        uses: actions/checkout@v2
        with:
          repository: ElemeFE/element
          ref: gh-pages
          path: element.eleme.io

      - name: Deploy element.eleme.io
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: element.eleme.io
          PUBLISH_DIR: ./element.eleme.io
        