name: GitHub Actions Build and Deploy Document Static
on:
  push:
    branches:
      - master
    tags:
      - v1.*
jobs:
  job-koajs:
    runs-on: ubuntu-18.04
    steps:
      - name: Get koajs Static
        uses: actions/checkout@v2
        with:
          repository: koajs/koajs.com
          ref: gh-pages
          path: koajs.com

      - name: Deploy koajs.com
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: koajs.com
          PUBLISH_DIR: ./koajs.com


  job-typeorm:
    needs: [job-koajs]
    runs-on: ubuntu-18.04
    steps:
      - name: Get typeorm Static
        uses: actions/checkout@v2
        with:
          repository: typeorm/typeorm.github.io
          ref: master
          path: typeorm.github.io

      - name: Deploy typeorm.github.io
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: typeorm.github.io
          PUBLISH_DIR: ./typeorm.github.io
        

  job-jest:
    needs: [job-koajs, job-typeorm]
    runs-on: ubuntu-18.04
    steps:
      - name: Get jestjs.io Static
        uses: actions/checkout@v2
        with:
          repository: facebook/jest
          ref: gh-pages
          path: jestjs.io

      - name: Deploy jestjs.io
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: jestjs.io
          PUBLISH_DIR: ./jestjs.io

  job-antd:
    needs: [job-koajs, job-typeorm, job-jest]
    runs-on: ubuntu-18.04
    steps:
      - name: Get ant.design Static
        uses: actions/checkout@v2
        with:
          repository: ant-design/ant-design
          ref: gh-pages
          path: ant.design

      - name: Deploy ant.design
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: ant.design
          PUBLISH_DIR: ./ant.design
        

  job-reactjs:
    needs: [job-koajs, job-typeorm, job-jest, job-antd]
    runs-on: ubuntu-18.04
    steps:
      - name: Get zh-hans.reactjs.org Static
        uses: actions/checkout@v2
        with:
          repository: reactjs/zh-hans.reactjs.org
          ref: gh-pages
          path: zh-hans.reactjs.org

      - name: Deploy zh-hans.reactjs.org
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: zh-hans.reactjs.org
          PUBLISH_DIR: ./zh-hans.reactjs.org
        

  job-element:
    needs: [job-koajs, job-typeorm, job-jest, job-antd, job-reactjs]
    runs-on: ubuntu-18.04
    steps:
      - name: Get element.eleme.io Static
        uses: actions/checkout@v2
        with:
          repository: ElemeFE/element
          ref: gh-pages
          path: element.eleme.io

      - name: Deploy element.eleme.io
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: element.eleme.io
          PUBLISH_DIR: ./element.eleme.io
        

  job-cnvuejs:
    needs: [job-koajs, job-typeorm, job-jest, job-antd, job-reactjs, job-element]
    runs-on: ubuntu-18.04
    steps:
      - name: Get cn.vuejs.org Static
        uses: actions/checkout@v2
        with:
          repository: vuejs/cn.vuejs.org
          ref: gh-pages
          path: cn.vuejs.org

      - name: Deploy cn.vuejs.org
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: cn.vuejs.org
          PUBLISH_DIR: ./cn.vuejs.org
        

  job-sequelize:
    needs: [job-koajs, job-typeorm, job-jest, job-antd, job-reactjs, job-element, job-cnvuejs]
    runs-on: ubuntu-18.04
    steps:
      - name: Get sequelize.org Static
        uses: actions/checkout@v2
        with:
          repository: sequelize/sequelize.org
          ref: gh-pages
          path: sequelize.org

      - name: Deploy sequelize.org
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: sequelize.org
          PUBLISH_DIR: ./sequelize.org
        

  job-expressjs:
    needs: [job-koajs, job-typeorm, job-jest, job-antd, job-reactjs, job-element, job-cnvuejs, job-sequelize]
    runs-on: ubuntu-18.04
    steps:
      - name: Get expressjs.com Static
        uses: actions/checkout@v2
        with:
          repository: expressjs/expressjs.com
          ref: gh-pages
          path: expressjs.com

      - name: Deploy expressjs.com
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: expressjs.com
          PUBLISH_DIR: ./expressjs.com
        