name: GitHub Actions Build and Deploy Document Static
on:
  push:
    branches:
      - master
jobs:
  deploy-react-native:
    runs-on: ubuntu-18.04
    steps:
      - name: Get react-native-doc Static
        uses: actions/checkout@v2
        with:
          repository: jaywcjlove/react-native-doc
          ref: gh-pages
          path: react-native-doc

      - name: Deploy react-native-doc
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: react-native
          PUBLISH_DIR: ./react-native-doc

  deploy-koajs:
    runs-on: ubuntu-18.04
    steps:
      - name: Get koajs Static
        uses: actions/checkout@v2
        with:
          repository: koajs/koajs.com
          ref: gh-pages
          path: koajs.com

      - name: Deploy koajs.com
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: koajs.com
          PUBLISH_DIR: ./koajs.com

  deploy-jestjs:
    runs-on: ubuntu-18.04
    steps:
      - name: Get jest Static
        uses: actions/checkout@v2
        with:
          repository: facebook/jest
          ref: gh-pages
          path: jestjs.io

      - name: Deploy jestjs.io
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: jestjs.io
          PUBLISH_DIR: ./jestjs.io

  deploy-typeorm:
    runs-on: ubuntu-18.04
    steps:
      - name: Get typeorm Static
        uses: actions/checkout@v2
        with:
          repository: typeorm/typeorm.github.io
          ref: master
          path: typeorm.github.io

      - name: Deploy typeorm.github.io
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: typeorm.github.io
          PUBLISH_DIR: ./typeorm.github.io
        