name: cn.vuejs.org
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
          registry-url: "https://registry.npmjs.org/"

      - name: Get Static
        run: |
          git clone https://github.com/vuejs/cn.vuejs.org -b gh-pages --single-branch cn.vuejs.org --depth 1

      - name: Deploy cn.vuejs.org
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: cn.vuejs.org
          publish_dir: ./cn.vuejs.org