name: deno-manual-cn
on:
  push:
    paths:
      - '.github/workflows/deno-manual-cn.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
          registry-url: "https://registry.npmjs.org/"

      - name: Get Static
        run: |
          git clone https://github.com/Nugine/deno-manual-cn -b gh-pages --single-branch deno-manual-cn --depth 1

      - name: Deploy deno-manual-cn
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deno-manual-cn
          publish_dir: ./deno-manual-cn