name: eslint.org
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
          registry-url: "https://registry.npmjs.org/"

      - name: Get Static
        run: |
          git clone https://github.com/eslint/website.git -b master --single-branch --depth 1 eslint.org

      - name: Build website
        run: |
          cd eslint.org/
          yarn install
          yarn run build

      - name: Deploy eslint.org
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: eslint.org
          publish_dir: ./eslint.org/_site