name: expressjs
on:
  push:
    # branches:
    #   - master
    paths:
      - '.github/workflows/expressjs.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
          registry-url: "https://registry.npmjs.org/"

      - name: Get Static
        run: |
          git clone https://github.com/expressjs/expressjs.com -b gh-pages --single-branch expressjs.com --depth 1

      - name: Deploy expressjs.com
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: expressjs.com
          publish_dir: ./expressjs.com