name: jestjs.io
on:
  push:
    # branches:
    #   - master
    paths:
      - '.github/workflows/jestjs.io.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
          registry-url: "https://registry.npmjs.org/"

      - name: Get Static
        run: |
          git clone https://github.com/facebook/jest -b gh-pages --single-branch jestjs.io --depth 1

      - name: Deploy jestjs.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: jestjs.io
          publish_dir: ./jestjs.io