name: koajs
on:
  push:
    # branches:
    #   - master
    paths:
      - '.github/workflows/koajs.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
          registry-url: "https://registry.npmjs.org/"

      - name: Get Static
        run: |
          git clone https://github.com/koajs/koajs.com -b gh-pages --single-branch koajs.com --depth 1

      - name: Deploy koajs.com
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: koajs.com
          publish_dir: ./koajs.com