name: typescriptlang.org
on:
  push:
    # branches:
    #   - master
    paths:
      - '.github/workflows/typescriptlang.org.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
          registry-url: "https://registry.npmjs.org/"
      - name: Echo directory size and order
        run: |
          git clone https://github.com/microsoft/TypeScript-website -b v2 --single-branch typescriptlang.org/website --depth 1

      # Build v2
      - name: Build website v2
        run: |
          cd typescriptlang.org/website
          yarn install
          yarn bootstrap
          yarn build
          yarn build-site
          cp -r packages/typescriptlang-org/public site
          cp -r site ../code

      - name: Deploy typescriptlang.org
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: typescriptlang.org
          publish_dir: ./typescriptlang.org/code