name: v3.cn.vuejs.org
on:
  push:
    paths:
      - '.github/workflows/v3.cn.vuejs.org.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - run: pnpm -v
      - run: node -v
      - run: npm -v

      - name: Get Static (Vue 3)
        run: |
          git clone https://github.com/vuejs-translations/docs-zh-cn.git -b main --single-branch v3.cn.vuejs.org --depth 1
      - run: pnpm i
        working-directory: v3.cn.vuejs.org

      - run: npm run build
        working-directory: v3.cn.vuejs.org
      - run: tree -I 'node_modules' -L 2

      - name: Deploy (vue3) v3.cn.vuejs.org
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: v3.cn.vuejs.org
          publish_dir: ./v3.cn.vuejs.org